import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Test from "../Components/Test";
export default function Home() {
  const text = "Hola estas son animaciones de prueba para framer motion xD";
  const obtainArrayOfLetters = (str) => {
    return str.split("");
  };

  const arrayOfLetters = obtainArrayOfLetters(text);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>
        {arrayOfLetters.map((word, i) => (
          <span key={i} className={styles.letter}>
            {word}
          </span>
        ))}
      </h1>
    </div>
  );
}
